# Generated by Django 4.2.8 on 2024-07-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
                ('is_passed', models.BooleanField()),
                ('passing_year', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('starting_date', models.CharField(max_length=255)),
                ('ending_date', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('completing_date', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
