# Generated by Django 4.2.8 on 2024-07-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_experience_projects_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='company_name',
        ),
    ]
